channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=25.1.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - graphviz==0.21
  - lightgbm==4.6.0
  - matplotlib==3.9.4
  - numpy==2.0.2
  - pandas==2.3.1
  - pyarrow==20.0.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
